### ISSUE TITLE
is this the same JavaCSS project from dev.net?

### ISSUE THREAD

**Issue by aplatypus** [rydnr/JavaCSS#1]
I am looking for this project:

- https://community.oracle.com/blogs/enicholas/2008/07/17/introducing-java-css

Which was had a good recommendation in this article:

- http://www.quepublishing.com/articles/article.aspx?p=1390174

Thanks

**Comment by rydnr** [comment]
I'm afraid it's not the same project.

This one uses CSS to specify how to format Java source files, not to change styles of Swing components.

Sorry.
